@startsalt
{
  {T} Questions
  [ Search ______________________________________ ]
  --
  * 1  ✓  "Tell me about yourself"            (Answered)
  * 2  •  "Stakeholder alignment example"     (In progress)
  * 3  ○  "Conflict you resolved"             (Review)
  * 4  •  "Impact you delivered"              (Not started)
  * 5  •  "Long‑term goals"                   (Not started)
  --
  [ Filter: (All ▼) ]  [ Close ]
}
@endsalt

