@startsalt
{
  {T} Review Voice Answer
  [........................................................................]
  [........................................................................]
  [........................................................................]
  --
  [ Cancel ]  [ Edit Text ]  [ Submit for Evaluation ]
}
@endsalt

